### ISSUE TITLE
Windows Insider Preview Downloads

### ISSUE THREAD

**Issue by Vichingo455** [massgravel/msdl#2]
Hi,
Can you please add Windows Insider Preview downloads?
It would be very useful and nice.

Thanks,
Vichingo455

**Comment by ave9858** [comment]
This isn't possible because Insider Preview ISOs require a Microsoft account enrolled in the Insider program. You can use https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewiso to download ISOs manually.
